services:
    database:
        image: mysql:8.0
        restart: always
        ports:
            -   "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            -   mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            -   "8080:80"
        environment:
            - PMA_ARBITRY=1
            - PMA_USER=user
            - PMA_PASSWORD=password
            - PMA_HOST=database
            - PMA_PORT=3306

volumes:
    mysql-data:
